# Server config
server:
  port: 5555

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

info:
  component: API Gateway

# Spring config
spring:
  application:
    name: gateway-service

# Eureka config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
    enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

# Ribbon config
ribbon:
  eureka:
    enabled: true

# Zuul config
zuul:
  prefix: /api
  routes:
    json-documents:
      path: /json/**
      serviceId: json-service
    xml-documents:
      path: /xml/**
      serviceId: xml-service
    txt-documents:
      path: /txt/**
      serviceId: txt-service
      

endpoints:
  routes:
    sensitive: false
  trace:
    sensitive: false